modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "miapi"
type = "required"
versionRange = "[2.3.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "create_sa"
type = "optional"
versionRange = "[2.1.4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "create_enchantment_industry"
type = "optional"
versionRange = "[2.4.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "immersiveenchanting"
type = "optional"
versionRange = "[5.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "creating_stories_workshop.mixins.json"
