# Creating Stories shader defaults. Players may safely change these in Video Settings.
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=ComplementaryReimagined_r5.8.1.zip
