modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
displayTest = "IGNORE_ALL_VERSION"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "jearchaeology"
type = "required"
versionRange = "[1.21.1-1.2.0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "idas"
type = "optional"
versionRange = "[1.13.7,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "integrated_villages"
type = "optional"
versionRange = "[1.3.3,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "just_enough_archaeology_integrations.mixins.json"
